version: '3.8'

services:
  postgres_test:
    image: postgres:13
    ports:
      - 5433:5432
    volumes:
      - type: tmpfs
        target: /var/lib/postgresql/data
      - type: tmpfs
        target: /dev/shm
    environment: 
      POSTGRES_PASSWORD: postgres